[window]
padding={x=10, y=10}
opacity=0.7

[font]
size=11.0

[font.normal]
family="Monaspace Neon Var"
style="Medium"

[font.italic]
family="Monaspace Radon Var"
style="Medium Italic"

[font.bold]
style="Bold"

[general]
import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

